"""add_deleted_at_for_soft_delete

Revision ID: 184bb0a338b8
Revises: 78852365d9a1
Create Date: 2025-12-25 10:34:16.863786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184bb0a338b8'
down_revision = '78852365d9a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molds', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.drop_column('molds', 'deleted_at')
    # ### end Alembic commands ###



