"""Add notifications table

Revision ID: 414d5f3aa5a4
Revises: 63e8ad10e142
Create Date: 2025-12-23 16:56:45.546420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414d5f3aa5a4'
down_revision = '63e8ad10e142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Notifications table already created in initial migration, skip it here
    # op.create_table('notifications', ...)  # Already exists in 63e8ad10e142
    op.drop_constraint('machines_name_key', 'machines', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('machines_name_key', 'machines', ['name'])
    op.drop_table('notifications')
    # ### end Alembic commands ###

