"""add_created_by_to_work_orders

Revision ID: 8468d88a1a24
Revises: d0b9240f0a85
Create Date: 2025-12-26 20:42:00.794276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8468d88a1a24'
down_revision = 'd0b9240f0a85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    # SQLite doesn't support ALTER TABLE ADD CONSTRAINT
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.create_foreign_key('fk_work_orders_created_by', 'work_orders', 'users', ['created_by'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_constraint('fk_work_orders_created_by', 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'created_by')
