"""add_produced_qty_to_work_orders

Revision ID: c096c50476ab
Revises: 1affabf2331a
Create Date: 2025-12-27 22:19:32.152464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c096c50476ab'
down_revision = '1affabf2331a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    
    # SQLite doesn't support ALTER COLUMN, so we add column with default directly
    if bind.dialect.name == 'sqlite':
        # For SQLite, add column with default value directly
        op.add_column('work_orders', sa.Column('produced_qty', sa.Integer(), nullable=False, server_default='0'))
    else:
        # For other databases, use the standard approach
        op.add_column('work_orders', sa.Column('produced_qty', sa.Integer(), nullable=True))
        # Mevcut kayıtlara 0 değerini ata
        op.execute("UPDATE work_orders SET produced_qty = 0 WHERE produced_qty IS NULL")
        # Kolonu NOT NULL yap ve default değer ekle
        op.alter_column('work_orders', 'produced_qty', nullable=False, server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'produced_qty')
    # ### end Alembic commands ###



